### ISSUE TITLE
euclidian mode

### ISSUE THREAD

**Issue by jojo-monk** [joeSeggiola/arduino-eurorack-projects#6]
Is it possible to add a possibility to switch to euclidian mode by double-clicking on the reset button?

**Comment by joeSeggiola** [comment]
Switching to Euclidean mode at run-time should be trivial: we can remove `const` to `bool EUCLIDEAN` at [line 19](https://github.com/joeSeggiola/arduino-eurorack-projects/blob/master/clock-divider/clock-divider.ino#L19), change its value at run-time, and everything should work. Only thing, maybe the counter should also be reset when switching, like `count = 0`.

To implement double-clicking detection for the button, I would store a "reset last pressed time" at [line 88](https://github.com/joeSeggiola/arduino-eurorack-projects/blob/master/clock-divider/clock-divider.ino#L88), and check there for a short amount of time on subsequent presses. Let me know if you'll try something similar, or I will try myself when I'll have some time.

Anyway I don't think this could be a PR I want to merge, since using the same reset button for three purposes could be confusing, and the double click is too easy to trigger by accident.
