### ISSUE TITLE
MCP4728 calibration standard

### ISSUE THREAD

**Issue by joeSeggiola** [joeSeggiola/arduino-eurorack-projects#7]
> Is C4 the standard for raising and lowering the voltage when performing calibration? 
In my case, I could raise or lower the voltage based on C3 not C4..

_Originally posted by @b2unit69 in https://github.com/joeSeggiola/arduino-eurorack-projects/issues/5#issuecomment-1501630759_

**Comment by joeSeggiola** [comment]
@b2unit69 Calibration process is not based on any particular note. For both In CV and MIDI 4+1, you calibrate the output voltage of the DACs, not notes. What are you referring to, exactly?

**Comment by b2unit69** [comment]
Yes, that's right. According to the document you provided, any note in the calibration process doesn't matter, but notes above C4 raise the output voltage, and notes below C4 lower the output voltage. But in my case, it was C3, not C4. That's why I asked because I wanted to check what I miswired or set up or because of the mcp4728.

C1-------C2-------C3-------C4+++++++C5+++++++C6 (in your document)

C1-------C2-------C3+++++++C4+++++++C5+++++++C6 (in my case)

ps. Thanks to you, I think I can also prepare a midi to cv module. almost done.

**Comment by joeSeggiola** [comment]
@b2unit69 Ah, I understand. In fact [my code uses MIDI note 60](https://github.com/joeSeggiola/arduino-eurorack-projects/blob/master/midi4plus1/midi4plus1.ino#L599) as the split point, which is defined as "middle C" in MIDI specification. That said, there is no consensus on labeling "middle C" as C3 or C4: if you look up online you'll find lot of resources saying one or the other. As Wikipedia puts it:

> For a classical piano and musical theory, the middle C is usually labelled as C4; However, in the [MIDI](https://en.wikipedia.org/wiki/MIDI) standard definition, this middle C (261.626 Hz) is labelled C3. In practice, a MIDI software can label middle C (261.626 Hz) as C3–C5, which can cause confusion

I think it's simply your controller that decided to label its middle C as C3 instead of C4, so it's just a naming issue. I will update the [README file](https://github.com/joeSeggiola/arduino-eurorack-projects/blob/master/midi4plus1/README.md) to reflect that and avoid confusion in future readers. Thanks.
